"""empty message

Revision ID: 4aeafa4b0c86
Revises: e293d026b9b7
Create Date: 2025-01-12 12:25:21.471261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aeafa4b0c86'
down_revision = 'e293d026b9b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recetas', schema=None) as batch_op:
        batch_op.alter_column('ingredients',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recetas', schema=None) as batch_op:
        batch_op.alter_column('ingredients',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###
