"""empty message

Revision ID: 5bc2cb622715
Revises: 49704edd414b
Create Date: 2024-12-28 14:03:55.124337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bc2cb622715'
down_revision = '49704edd414b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receta_favorita', schema=None) as batch_op:
        batch_op.drop_constraint('receta_favorita_receta_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'recetas', ['receta_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receta_favorita', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('receta_favorita_receta_id_fkey', 'recetas', ['receta_id'], ['id'])

    # ### end Alembic commands ###
