"""empty message

Revision ID: d7f9425e790e
Revises: 5bc2cb622715
Create Date: 2025-01-06 21:45:11.930000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7f9425e790e'
down_revision = '5bc2cb622715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receta_favorita', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_agregado', sa.DateTime(), nullable=True))

    with op.batch_alter_table('receta_ingredientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad', sa.String(length=50), nullable=True))
        batch_op.drop_constraint('receta_ingredientes_receta_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('receta_ingredientes_ingrediente_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'recetas', ['receta_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'ingredientes', ['ingrediente_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('recetas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('popularidad', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('visibilidad', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('origen', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recetas', schema=None) as batch_op:
        batch_op.drop_column('origen')
        batch_op.drop_column('visibilidad')
        batch_op.drop_column('popularidad')

    with op.batch_alter_table('receta_ingredientes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('receta_ingredientes_ingrediente_id_fkey', 'ingredientes', ['ingrediente_id'], ['id'])
        batch_op.create_foreign_key('receta_ingredientes_receta_id_fkey', 'recetas', ['receta_id'], ['id'])
        batch_op.drop_column('cantidad')

    with op.batch_alter_table('receta_favorita', schema=None) as batch_op:
        batch_op.drop_column('fecha_agregado')

    # ### end Alembic commands ###
