"""empty message

Revision ID: e293d026b9b7
Revises: d7f9425e790e
Create Date: 2025-01-11 19:27:44.492258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e293d026b9b7'
down_revision = 'd7f9425e790e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recetas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredients', sa.String(length=200), nullable=True))
        batch_op.alter_column('descripcion',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('pasos',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recetas', schema=None) as batch_op:
        batch_op.alter_column('pasos',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('descripcion',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('ingredients')

    # ### end Alembic commands ###
